// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef app_h
#define app_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Input.H>
extern Fl_Input *MIDText;
#include <FL/Fl_Button.H>
extern Fl_Input *WAVText;
Fl_Double_Window* make_window();
extern int getfile(Fl_Input*,char*,int);
#include "honkconv.h"
#endif
